#!/bin/bash
# NEXTFLOW TASK: 2E_bismark_summary
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /Myvolume/fyan0011/GitHub/RRBS_nf/work/f0/8087ec853eb5136b54eb380a78b68a/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /Myvolume/fyan0011/GitHub/RRBS_nf/work/f0/8087ec853eb5136b54eb380a78b68a/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f input.1
    rm -f sample_R1_val_1.fq_trimmed_bismark_hisat2_pe.bam
    rm -f input.3
    rm -f sample_R1_val_1.fq_trimmed_bismark_hisat2_PE_report.txt
    rm -f input.5
    rm -f sample_R1_val_1.fq_trimmed_bismark_hisat2_pe_splitting_report.txt
    rm -f input.7
    rm -f sample_R1_val_1.fq_trimmed_bismark_hisat2_pe.M-bias.txt
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/tmp/72/cc100cea3f97cc4c556883cacae893/input.1 input.1
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/07/18b28ccd8533850c5e9370a03d4bcf/sample_R1_val_1.fq_trimmed_bismark_hisat2_pe.bam sample_R1_val_1.fq_trimmed_bismark_hisat2_pe.bam
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/tmp/a7/b8f4c860c111f8e23fc5ba3e8b6596/input.3 input.3
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/07/18b28ccd8533850c5e9370a03d4bcf/sample_R1_val_1.fq_trimmed_bismark_hisat2_PE_report.txt sample_R1_val_1.fq_trimmed_bismark_hisat2_PE_report.txt
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/tmp/1c/4916867b968339d39b2761936e7fe9/input.5 input.5
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/21/20e76627007f43b907a7ad582dc5d3/sample_R1_val_1.fq_trimmed_bismark_hisat2_pe_splitting_report.txt sample_R1_val_1.fq_trimmed_bismark_hisat2_pe_splitting_report.txt
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/tmp/39/96c37be2e3fbca80e59f5e9c55190b/input.7 input.7
    ln -s /Myvolume/fyan0011/GitHub/RRBS_nf/work/21/20e76627007f43b907a7ad582dc5d3/sample_R1_val_1.fq_trimmed_bismark_hisat2_pe.M-bias.txt sample_R1_val_1.fq_trimmed_bismark_hisat2_pe.M-bias.txt
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR1 USR2

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Myvolume/fyan0011/GitHub/RRBS_nf/work/f0/8087ec853eb5136b54eb380a78b68a/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
